set(PROJECT_BUILD_JSON_FILE "${CMAKE_SOURCE_DIR}/build.json")
if(NOT EXISTS ${PROJECT_BUILD_JSON_FILE})
  message(FATAL_ERROR "cannot find build.json: ${PROJECT_BUILD_JSON_FILE}")
endif()

file(READ ${PROJECT_BUILD_JSON_FILE} PROJECT_BUILD_JSON)
string(JSON BUILD_JSON_NAME GET ${PROJECT_BUILD_JSON} "name")
string(JSON BUILD_JSON_VERSION GET ${PROJECT_BUILD_JSON} "version")
string(JSON BUILD_JSON_HOMEPAGE GET ${PROJECT_BUILD_JSON} "homepage")
